name: Tests & CI Releases

on:
  workflow_dispatch:
  # Trigger on new tags (e.g. v1.2.3)
  push:
    tags:
      - 'v*'

jobs:
  manual-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Run tests manually
        run: dotnet test ./src/

  release:
      needs: manual-test
      if: ${{ github.event_name == 'push' }}
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
          with:
            lfs: true

        - name: Show Directory
          run: ls ./src/MuMu_RichPresence.Tests/Assets
          shell: powershell

        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'

        - name: Run tests before release
          run: dotnet test ./src/

        - name: Install Velopack tool
          run: make install_velopack

        - name: Build and Package Release
          run: make velopack VERSION="${GITHUB_REF#refs/tags/v}

        - name: Create GitHub Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref_name }}
            release_name: ${{ github.ref_name }}
            body: |
              **Dependencies**
              - [.NET 8.0 Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.8-windows-x64-installer)

        - name: Upload assets from bin folder
          run: |
            echo "Uploading files from ./bin/..."
            for file in $(find ./bin -type f); do
              echo "Uploading $file"
              gh release upload ${{ github.ref_name }} "$file" --clobber
            done

        - name: Upload assets from velopack folder
          run: |
            echo "Uploading files from ./velopack/..."
            for file in $(find ./velopack -type f); do
              echo "Uploading $file"
              gh release upload ${{ github.ref_name }} "$file" --clobber
            done